import { BrowserContext, Page } from 'playwright';
import {
  RecorderActionSummary,
  RecorderExtractSuggestion,
  RecorderPrecheckIssue,
} from '../../src/common/types/recorder.types';

export type RecorderActionRecord =
  | {
      id: string;
      type: 'open_page';
      label: string;
      url: string;
    }
  | {
      id: string;
      type: 'click';
      label: string;
      selector: string;
    }
  | {
      id: string;
      type: 'input';
      label: string;
      selector: string;
      value: string;
      parameterKey?: string;
      parameterLabel?: string;
      parameterDescription?: string;
      useRuntimeInput?: boolean;
    }
  | {
      id: string;
      type: 'press_key';
      label: string;
      key: string;
    }
  | {
      id: string;
      type: 'scroll';
      label: string;
      direction: 'up' | 'down' | 'top' | 'bottom';
      distance?: number;
    }
  | {
      id: string;
      type: 'wait_for_url';
      label: string;
      url: string;
      linkedActionId?: string;
      autoGenerated?: boolean;
    };

export interface RecorderSession {
  id: string;
  ownerId: string;
  name: string;
  context: BrowserContext;
  page: Page;
  actions: RecorderActionRecord[];
  latestScreenshotBase64: string;
  latestMimeType: string;
  latestUpdatedAt: string;
  suggestions: RecorderExtractSuggestion[];
  precheckIssues: RecorderPrecheckIssue[];
  stopScreenshotLoop: () => void;
}

export function createRecorderActionId() {
  return `rec-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function isRecorderWaitForUrlAction(
  action: RecorderActionRecord,
): action is Extract<RecorderActionRecord, { type: 'wait_for_url' }> {
  return action.type === 'wait_for_url';
}

export function getRecorderActionGroupLength(
  actions: RecorderActionRecord[],
  startIndex: number,
) {
  const startAction = actions[startIndex];

  if (!startAction) {
    return 0;
  }

  if (isRecorderWaitForUrlAction(startAction)) {
    return 1;
  }

  let length = 1;
  let cursor = startIndex + 1;

  while (cursor < actions.length) {
    const nextAction = actions[cursor];

    if (
      !nextAction ||
      !isRecorderWaitForUrlAction(nextAction) ||
      nextAction.linkedActionId !== startAction.id
    ) {
      break;
    }

    length += 1;
    cursor += 1;
  }

  return length;
}

export function findPreviousRecorderActionStart(
  actions: RecorderActionRecord[],
  startIndex: number,
) {
  for (let index = startIndex - 1; index >= 0; index -= 1) {
    if (!isRecorderWaitForUrlAction(actions[index])) {
      return index;
    }
  }

  return -1;
}

export function findNextRecorderActionStart(
  actions: RecorderActionRecord[],
  startIndex: number,
) {
  const currentGroupLength = getRecorderActionGroupLength(actions, startIndex);

  for (
    let index = startIndex + currentGroupLength;
    index < actions.length;
    index += 1
  ) {
    if (!isRecorderWaitForUrlAction(actions[index])) {
      return index;
    }
  }

  return -1;
}

export function replaceRecorderActions(
  session: RecorderSession,
  actions: RecorderActionRecord[],
) {
  session.actions.splice(0, session.actions.length, ...actions);
}

export function normalizeRecorderParameterKey(value: string) {
  const normalized = value
    .trim()
    .replace(/[\s\-]+/g, '_')
    .replace(/[^\w]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();

  return normalized || `field_${Math.random().toString(36).slice(2, 6)}`;
}

export function createRecorderPrecheckIssue(
  level: RecorderPrecheckIssue['level'],
  message: string,
  actionId?: string,
): RecorderPrecheckIssue {
  return {
    id: `rec-issue-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    level,
    message,
    actionId,
  };
}

export function truncateRecorderPreview(value: string, maxLength = 80) {
  const normalized = value.replace(/\s+/g, ' ').trim();

  if (!normalized) {
    return '';
  }

  return normalized.length > maxLength
    ? `${normalized.slice(0, maxLength)}...`
    : normalized;
}

export function invalidateRecorderAnalysis(session: RecorderSession) {
  session.precheckIssues = [];
  session.suggestions = [];
}

export function toRecorderActionSummary(
  action: RecorderActionRecord,
): RecorderActionSummary {
  if (action.type === 'open_page') {
    return {
      id: action.id,
      type: action.type,
      label: action.label,
      url: action.url,
    };
  }

  if (action.type === 'click') {
    return {
      id: action.id,
      type: action.type,
      label: action.label,
      selector: action.selector,
    };
  }

  if (action.type === 'input') {
    return {
      id: action.id,
      type: action.type,
      label: action.label,
      selector: action.selector,
      value: action.value,
      useRuntimeInput: action.useRuntimeInput,
      parameterKey: action.parameterKey,
      parameterLabel: action.parameterLabel,
      parameterDescription: action.parameterDescription,
    };
  }

  if (action.type === 'press_key') {
    return {
      id: action.id,
      type: action.type,
      label: action.label,
      key: action.key,
    };
  }

  if (action.type === 'scroll') {
    return {
      id: action.id,
      type: action.type,
      label: action.label,
      direction: action.direction,
      distance: action.distance,
    };
  }

  return {
    id: action.id,
    type: action.type,
    label: action.label,
    url: action.url,
    linkedActionId: action.linkedActionId,
    autoGenerated: action.autoGenerated,
  };
}
