import { WorkflowDefinition } from './workflow.types';

export type RecorderCommandType =
  | 'create'
  | 'navigate'
  | 'click'
  | 'input'
  | 'press_key'
  | 'scroll'
  | 'update_action'
  | 'move_action'
  | 'delete_action'
  | 'clear_actions'
  | 'resume_from_action'
  | 'analyze'
  | 'precheck'
  | 'snapshot'
  | 'finish'
  | 'close';

export type RecorderActionType =
  | 'open_page'
  | 'click'
  | 'input'
  | 'press_key'
  | 'scroll'
  | 'wait_for_url';

export type RecorderWorkflowMode = 'workflow' | 'template';

export interface RecorderActionUpdatePayload {
  label?: string;
  selector?: string;
  value?: string;
  url?: string;
  key?: string;
  direction?: 'up' | 'down' | 'top' | 'bottom';
  distance?: number;
  parameterKey?: string;
  parameterLabel?: string;
  parameterDescription?: string;
  useRuntimeInput?: boolean;
}

export interface RecorderCommandPayload extends RecorderActionUpdatePayload {
  requestId: string;
  sessionId: string;
  ownerId?: string;
  type: RecorderCommandType;
  xRatio?: number;
  yRatio?: number;
  actionId?: string;
  moveDirection?: 'up' | 'down';
  name?: string;
  mode?: RecorderWorkflowMode;
}

export interface RecorderActionSummary {
  id: string;
  type: RecorderActionType;
  label: string;
  selector?: string;
  value?: string;
  url?: string;
  key?: string;
  direction?: 'up' | 'down' | 'top' | 'bottom';
  distance?: number;
  linkedActionId?: string;
  autoGenerated?: boolean;
  useRuntimeInput?: boolean;
  parameterKey?: string;
  parameterLabel?: string;
  parameterDescription?: string;
}

export interface RecorderExtractSuggestion {
  id: string;
  label: string;
  selector: string;
  property: 'text' | 'html' | 'href' | 'src' | 'value' | 'attribute';
  targetMode: 'first' | 'all' | 'count';
  preview: string;
  saveKey: string;
  collectionKey?: string;
  collectionName?: string;
  recommendedRecordMode?: 'single' | 'array';
}

export interface RecorderPrecheckIssue {
  id: string;
  level: 'warning' | 'error';
  message: string;
  actionId?: string;
}

export interface RecorderSessionDelta {
  kind:
    | 'snapshot'
    | 'action_added'
    | 'action_updated'
    | 'action_deleted'
    | 'actions_cleared'
    | 'actions_reordered'
    | 'resumed'
    | 'analysis_updated'
    | 'precheck_updated';
  actionId?: string;
  timestamp: string;
}

export interface RecorderSessionSnapshot {
  sessionId: string;
  ownerId: string;
  pageUrl: string;
  imageBase64: string;
  mimeType: string;
  updatedAt: string;
  viewport: {
    width: number;
    height: number;
  };
  actionCount: number;
  actions: RecorderActionSummary[];
  suggestions: RecorderExtractSuggestion[];
  precheckIssues: RecorderPrecheckIssue[];
}

export interface RecorderLiveEvent {
  sessionId: string;
  ownerId: string;
  snapshot: RecorderSessionSnapshot;
  delta?: RecorderSessionDelta;
}

export interface RecorderCommandResult {
  ok: boolean;
  sessionId: string;
  pageUrl?: string;
  snapshot?: RecorderSessionSnapshot;
  action?: RecorderActionSummary;
  definition?: WorkflowDefinition;
  recommendedName?: string;
  suggestions?: RecorderExtractSuggestion[];
  precheckIssues?: RecorderPrecheckIssue[];
  error?: string;
}
